In [5]:
# Loading necessary libraries for data analysis and visualization. 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

In [6]:
df = pd.read_csv("../data/processed/3_ticket_prices_and_surcharges.csv")

df.head()

,month,conflict_phase,airline,iata_code,country,region,airline_type,route_class,avg_route_km,base_fare_usd,...,load_factor_pct,fuel_cost_pct_opex,yoy_price_change_pct,km_range,surcharge_band,fuel_surcharge_usd_surcharge_policy,brent_crude_usd_barrel,jet_fuel_usd_barrel_surcharge_policy,surcharge_as_pct_base,yoy_surcharge_change_pct
0,2019-01,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1179.91,...,79.4,0.209,NaN,4501–9000 km,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-02,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1176.08,...,89.0,0.216,NaN,4501–9000 km,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-03,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1133.88,...,64.1,0.246,NaN,4501–9000 km,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-04,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1237.95,...,75.1,0.225,NaN,4501–9000 km,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-05,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1270.08,...,85.8,0.268,NaN,4501–9000 km,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Basic review of the dataset
print("Shape:", df.shape)
print("\nColumns:", df.columns)

df.info()
df.describe()

Shape: (14355, 25)

Columns: Index(['month', 'conflict_phase', 'airline', 'iata_code', 'country', 'region',
       'airline_type', 'route_class', 'avg_route_km', 'base_fare_usd',
       'fuel_surcharge_usd', 'taxes_fees_usd', 'total_fare_usd',
       'brent_crude_usd', 'jet_fuel_usd_barrel', 'load_factor_pct',
       'fuel_cost_pct_opex', 'yoy_price_change_pct', 'km_range',
       'surcharge_band', 'fuel_surcharge_usd_surcharge_policy',
       'brent_crude_usd_barrel', 'jet_fuel_usd_barrel_surcharge_policy',
       'surcharge_as_pct_base', 'yoy_surcharge_change_pct'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14355 entries, 0 to 14354
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   month                                 14355 non-null  object
 1   conflict_phase                        14355 non-null  object
 2   airline                               14355 non-null  object
 3   iata_code                             14355 non-null  object
 4   country                               14355 non-null  object
 5   region                                14355 non-null  object
 6   airline_type                          14355 non-null  object
 7   route_class                           14355 non-null  object
 8   avg_route_km                          14355 non-null  int64
 9   base_fare_usd                         14355 non-null  float64
 10  fuel_surcharge_usd                    14355 non-null  float64
 11  taxes_fees_usd                        14355 non-null  float64
 12  total_fare_usd                        14355 non-null  float64
 13  brent_crude_usd                       14355 non-null  float64
 14  jet_fuel_usd_barrel                   14355 non-null  float64
 15  load_factor_pct                       14355 non-null  float64
 16  fuel_cost_pct_opex                    14355 non-null  float64
 17  yoy_price_change_pct                  12375 non-null  float64
 18  km_range                              14355 non-null  object
 19  surcharge_band                        10875 non-null  object
 20  fuel_surcharge_usd_surcharge_policy   10875 non-null  float64
 21  brent_crude_usd_barrel                10875 non-null  float64
 22  jet_fuel_usd_barrel_surcharge_policy  10875 non-null  float64
 23  surcharge_as_pct_base                 10875 non-null  float64
 24  yoy_surcharge_change_pct              9375 non-null   float64
dtypes: float64(14), int64(1), object(10)
memory usage: 2.7+ MB

,avg_route_km,base_fare_usd,fuel_surcharge_usd,taxes_fees_usd,total_fare_usd,brent_crude_usd,jet_fuel_usd_barrel,load_factor_pct,fuel_cost_pct_opex,yoy_price_change_pct,fuel_surcharge_usd_surcharge_policy,brent_crude_usd_barrel,jet_fuel_usd_barrel_surcharge_policy,surcharge_as_pct_base,yoy_surcharge_change_pct
count,14355.000000,14355.000000,14355.000000,14355.000000,14355.000000,14355.000000,14355.000000,14355.000000,14355.000000,12375.000000,10875.000000,10875.000000,10875.000000,10875.000000,9375.000
mean,5660.000000,897.978795,111.446290,125.921688,1135.346773,80.184368,93.624138,70.321477,0.280993,36.495865,70.126322,80.184368,93.624138,25.344041,inf
std,4964.284114,1141.206888,183.460396,164.178072,1468.411496,24.359421,28.371276,16.610219,0.096425,105.873915,99.601207,24.359693,28.371592,23.084279,NaN
min,800.000000,11.800000,0.190000,1.310000,13.890000,20.550000,23.690000,31.000000,0.052000,-80.330000,0.000000,20.550000,23.690000,0.000000,-100.000
25%,1500.000000,118.575000,10.820000,15.390000,146.460000,66.500000,76.870000,64.900000,0.223000,-23.660000,10.300000,66.500000,76.870000,7.800000,-40.935
50%,3500.000000,375.480000,35.640000,50.770000,470.560000,82.610000,94.920000,73.800000,0.277000,1.920000,29.620000,82.610000,94.920000,20.660000,23.060
75%,8500.000000,1253.130000,144.105000,177.415000,1565.400000,91.480000,109.200000,82.800000,0.335000,32.575000,92.890000,91.480000,109.200000,37.555000,202.350
max,14000.000000,8717.680000,2388.260000,1470.310000,12126.260000,169.080000,193.200000,92.000000,0.733000,518.100000,890.420000,169.080000,193.200000,150.930000,inf