In [2]:
import pandas as pd
import numpy as np

# load dataset
df = pd.read_csv("../data/cleaned_dataset/cleaned_ticket_prices.csv")

df.head()

,month,conflict_phase,airline,iata_code,country,region,airline_type,route_class,avg_route_km,base_fare_usd,...,yoy_surcharge_change_pct,year,month_num,quarter,is_extreme_fare,fuel_surcharge_ratio,taxes_ratio,base_ratio,crude_jet_ratio,fare_per_km
0,2019-01,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1179.91,...,0.0,2019,1,2019Q1,False,0.0731,0.1171,0.8098,1.1838,0.1714
1,2019-02,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1176.08,...,0.0,2019,2,2019Q1,False,0.0468,0.0933,0.8599,1.2087,0.1609
2,2019-03,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1133.88,...,0.0,2019,3,2019Q1,False,0.0857,0.0876,0.8267,1.1672,0.1614
3,2019-04,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1237.95,...,0.0,2019,4,2019Q2,False,0.0402,0.1155,0.8442,1.1320,0.1725
4,2019-05,Pre-Pandemic Baseline,ANA,NH,Japan,Asia,Flag Carrier,Long-Haul,8500,1270.08,...,0.0,2019,5,2019Q2,False,0.0570,0.1119,0.8311,1.1913,0.1798

KPI Calculations

KPI 1 — Price Pass-through (Fuel → Fare impact)

In [6]:
df['price_pass_through'] = df['total_fare_usd'] / df['jet_fuel_usd_barrel']
df[['total_fare_usd','jet_fuel_usd_barrel','price_pass_through']].head()

   total_fare_usd  jet_fuel_usd_barrel  price_pass_through
0         1457.07                74.58           19.537007
1         1367.65                81.72           16.735805
2         1371.61                76.87           17.843242
3         1466.34                73.34           19.993728
4         1528.12                72.97           20.941757